### ISSUE TITLE
If the webapp crashes, there's no logs to be seen about it except that it crashed

### ISSUE THREAD

**Issue by samip5** [netbootxyz/docker-netbootxyz#49]
I would love to be able to debug why the webapp crashes but I cannot find anything about why...

**Comment by samip5** [comment]
Related:

```
27b6dc3a2b76:/app# NODE_ENV=production,PORT=3000 /usr/bin/node app.js
listening on *:3000
8UGMCpMb-sANl0xKAAAB connected time=1697794923813
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Response status was 404
    at ClientRequest.<anonymous> (/app/node_modules/node-downloader-helper/dist/index.js:1:9452)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
Emitted 'error' event on b instance at:
    at ClientRequest.<anonymous> (/app/node_modules/node-downloader-helper/dist/index.js:1:9583)
    at Object.onceWrapper (node:events:628:26)
    [... lines matching original stack trace ...]
    at Readable.push (node:internal/streams/readable:234:10) {
  status: 404,
  body: ''
}

Node.js v18.16.1
```

I don't think it should crash if that's the case...
